deal with n_controllers=1
qua-platform/py-qua-tools pull request #153
Opened 2023-02-05 15:52 UTC by tomerfqm

2023-02-05 20:18 UTC, yomach reviewed
Add to changelog

2023-02-07 14:26 UTC, yomach requested changes

2023-02-07 14:26 UTC, yomach commented on CHANGELOG.md
> +- simulator_tools.create_simulator_controller_connections - now deals with the case of 1 controller.
I would put it under fixed

2023-02-07 14:26 UTC, yomach commented on CHANGELOG.md
> -- A new tool for discriminating two states in the IQ blob under `analysis.discriminator`
Why did you delete everything here?

2023-02-07 14:26 UTC, yomach commented on CHANGELOG.md
> +- A new tool f
?

2023-02-12 08:35 UTC, tomerfqm commented on CHANGELOG.md
> +- A new tool f
wtf..

2023-02-12 08:47 UTC, yomach commented on CHANGELOG.md
> -- A new tool for discriminating two states in the IQ blob under `analysis.discriminator`
that is why we have code reviews even for stupid stuff :)

2023-02-23 16:01 UTC, TheoLaudatQM approved these changes

2023-02-23 16:06 UTC, yomach approved these changes

2023-02-23 16:06 UTC, merged