set workflows for pre-release and released
qua-platform/py-qua-tools pull request #16
Opened 2021-08-03 18:22 UTC by sagiQM

Will deploy to pypi in case of publish release with no pre-release checkbox
In case pre-release checkbox is on then build and upload as github job asset

2021-08-04 08:43 UTC, qguyk requested changes

2021-08-04 08:43 UTC, qguyk commented on .github/workflows/on-released.yml
> +        run: |
please upload the assets to github as well (same as pre-release)

2021-08-04 14:32 UTC, qguyk approved these changes

2021-08-05 06:36 UTC, galwiner approved these changes

2021-08-05 06:38 UTC, merged