Add calibration result plotting functions
qua-platform/py-qua-tools pull request #234
Opened 2024-10-22 13:34 UTC by paulQM

Added tools to plot the mixer calibration results. 

`show_lo_result()` and `show_if_result()` plot the calibration data of the LO leakage and image sideband as well as the chosen calibration parameters: `I_0`, `Q_O`, `dc_gain` and `dc_phase`.

2024-10-22 13:37 UTC, paulQM commented
Missing:
- [ ] Modify changelog
- [ ] Write Readme documentation 
- [ ] Docstrings
- [ ] Tests

2024-10-25 08:32 UTC, TheoLaudatQM reviewed
Looks good, can we also add a function to extract the resulting LO leakage and image in dBm?

2024-10-25 08:32 UTC, TheoLaudatQM commented on qualang_tools/octave_tools/calibration_result_plotter.py
> +    )
Maybe it will look nicer with a box: `bbox=dict(facecolor='none', edgecolor='black', boxstyle='round,pad=1')`

2025-01-20 12:51 UTC, TheoLaudatQM requested changes
I started the review and many comments apply to all functions, namely:

- instead of an empty `return`, I think that raising an error makes more sense since it indicates to the user that something went wrong and it also indicates what.
- In general it would be nice to add comments explaining what the different parts of the code do so that we (CS) can maintain it later.
- It looks like there are a lot of sections that are common to the different functions, isn't it possible to break them down into small private functions (`def _function_name()`) that can be called in the main functions. It will make the code more readable and easier to test and maintain. 
I even think that using a class could make sense here, what do you think?

2025-01-20 12:51 UTC, TheoLaudatQM commented on qualang_tools/octave_tools/calibration_result_plotter.py
> +        data (MixerCalibrationResults): A dictionary containing the calibration results.
Here I would add that it is the output of `qm.calibrate_element()`

2025-01-20 12:51 UTC, TheoLaudatQM commented on qualang_tools/octave_tools/calibration_result_plotter.py
> +            return
Raising an error here instead would make more sense no?

2025-01-20 12:51 UTC, TheoLaudatQM commented on qualang_tools/octave_tools/calibration_result_plotter.py
> +        output_gain = list(data.keys())[0][1]
This looks risky to me, because of the non controlled ordering of the dictionary keys, why not simply accessing it with the correct key?

2025-01-20 12:51 UTC, TheoLaudatQM commented on qualang_tools/octave_tools/calibration_result_plotter.py
> +    # plt.title(f"LO auto calibration @ {lo_freq/1e9:.3f}GHz")
remove comments if not used

2025-01-20 12:51 UTC, TheoLaudatQM commented on qualang_tools/octave_tools/calibration_result_plotter.py
> +        return
Raising an error here instead would make more sense no?

2025-01-20 12:51 UTC, TheoLaudatQM commented on qualang_tools/octave_tools/calibration_result_plotter.py
> +        return
Need to expose to the user why the function returns nothing

2025-01-20 12:51 UTC, TheoLaudatQM commented on qualang_tools/octave_tools/calibration_result_plotter.py
> +def show_lo_result(
`show_lo_leakage_calibration_result()` makes more sense I think

2025-01-20 12:51 UTC, TheoLaudatQM commented on qualang_tools/octave_tools/calibration_result_plotter.py
> +def show_if_result(
`show_image_rejection_calibration_result()` makes more sense I think

2025-01-20 12:51 UTC, TheoLaudatQM commented on qualang_tools/octave_tools/calibration_result_plotter.py
> +def get_lo_suppression(
`get_lo_leakage_rejection()` makes more sense I think

2025-01-20 12:51 UTC, TheoLaudatQM commented on qualang_tools/octave_tools/calibration_result_plotter.py
> +def get_if_suppression(
`get_image_rejection()` makes more sense I think

2025-02-14 14:34 UTC, TheoLaudatQM requested changes
Great job, after these we'll be ready to merge :)

2025-02-14 14:34 UTC, TheoLaudatQM commented on qualang_tools/octave_tools/calibration_result_plotter.py
> +    return None
Why is this not a private method of the class?

2025-02-14 14:34 UTC, TheoLaudatQM commented on qualang_tools/octave_tools/calibration_result_plotter.py
> +        and returns the achieved image suppression in dB.
I would also specify that the displayed powers correspond to the powers measured by the OPX after up and down conversion and may differ significantly from the power outputted by the Octave, or something along these lines
A well as the meaning of dB here "Here the returned value is with respect to before the calibration (so taking into account the previously load calibration parameters), or without any parameters?"

2025-02-14 14:34 UTC, TheoLaudatQM commented on qualang_tools/octave_tools/calibration_result_plotter.py
> +        If the IF frequency is not given, the first IF frequency in the data is used.
The Lo and IF are not part of the input arguments, are they?

2025-02-14 14:34 UTC, TheoLaudatQM commented on qualang_tools/octave_tools/calibration_result_plotter.py
> +            float: The reduction of Image sideband power before vs after calibration in dB units.
I would again specify in dB with respect to what

2025-02-14 14:34 UTC, TheoLaudatQM commented on qualang_tools/octave_tools/calibration_result_plotter.py
> +
The Lo and IF are not part of the input arguments, are they?

2025-02-14 14:34 UTC, TheoLaudatQM commented on qualang_tools/octave_tools/calibration_result_plotter.py
> +            float: The reduction of LO leakage power before vs after calibration in dB units.
I would again specify in dB with respect to what

2025-02-17 12:19 UTC, paulQM commented on qualang_tools/octave_tools/README.md
> +Returns the LO leakage supression in dB after calibration compared to the leakage without calibration.
Without any parameters.

2025-02-17 13:51 UTC, paulQM commented on qualang_tools/octave_tools/README.md
> +![image](https://github.com/user-attachments/assets/329755f9-cbdc-4a73-aff5-0e6417c41924)
What do these actual mean? Should we just remove them altogether to not confuse the users?

2025-02-18 10:07 UTC, TheoLaudatQM commented on qualang_tools/octave_tools/README.md
> +![image](https://github.com/user-attachments/assets/329755f9-cbdc-4a73-aff5-0e6417c41924)
Yeah I am not sure either, so let's remove it altogether

2025-02-18 17:08 UTC, TheoLaudatQM approved these changes

2025-02-18 17:22 UTC, merged